# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "swingme"
mod.name = "SwingMe"
mod.group = "com.swingme"
mod.version = "1.0.0"

deps.fabric_loader = "0.19.3"
loomx.loom_version = "1.17-SNAPSHOT"

["26.1"]
mod.mc_compat = "~26.1"
mod.mc_releases = ["26.1", "26.1.1", "26.1.2"]

deps.fabric_api = "0.144.1+26.1"
deps.midnightlib_version = "1.9.3+26.1-fabric"
deps.hm_api_version = "1.0.3+26.1"
deps.modmenu_version = "18.0.0-alpha.8"

["26.2"]
mod.mc_compat = "~26.2"
mod.mc_releases = ["26.2"]

deps.fabric_api = "0.155.2+26.2"
deps.midnightlib_version = "1.9.3+26.2-fabric"
deps.hm_api_version = "1.0.4+26.2"
deps.modmenu_version = "20.0.1"